language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
    - "postgres"
before_script:
  - "psql -c 'create database forsetti_test;' -U postgres"
  - npm run pretest
script:
  - npm ci
  - npm test
